# Generated by Django 5.1.8 on 2025-05-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_id", models.IntegerField()),
                ("patient_id", models.IntegerField()),
                ("doctor_id", models.IntegerField()),
                ("ket_luan", models.TextField()),
                ("chan_doan", models.TextField()),
                ("dieu_tri", models.TextField()),
                ("ghi_chu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
