# Generated by Django 5.1.8 on 2025-05-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mat_khau", models.CharField(max_length=100)),
                ("ngay_sinh", models.DateField()),
                ("gioi_tinh", models.CharField(max_length=10)),
                ("so_dt", models.CharField(max_length=15)),
            ],
        ),
    ]
