# Generated by Django 5.1.8 on 2025-05-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="mat_khau",
            field=models.CharField(max_length=128),
        ),
    ]
