# Generated by Django 5.1.8 on 2025-05-25 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_patient_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="dia_chi",
            field=models.CharField(default="Không xác định", max_length=255),
        ),
        migrations.CreateModel(
            name="HealthInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ma_bao_hiem", models.CharField(max_length=20, unique=True)),
                ("ngay_cap", models.DateField()),
                ("ngay_het_han", models.DateField()),
                ("noi_cap", models.CharField(max_length=100)),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("con_hieu_luc", "Còn hiệu lực"),
                            ("het_han", "Hết hạn"),
                        ],
                        default="con_hieu_luc",
                        max_length=20,
                    ),
                ),
                ("muc_huong", models.IntegerField(default=80)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_insurances",
                        to="patient.patient",
                    ),
                ),
            ],
        ),
    ]
