# Generated by Django 5.1.8 on 2025-05-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_id", models.IntegerField()),
                ("doctor_id", models.IntegerField()),
                ("ngay_kham", models.DateField()),
                ("gio_kham", models.TimeField()),
                (
                    "trang_thai",
                    models.CharField(
                        choices=[
                            ("cho_xac_nhan", "Chờ xác nhận"),
                            ("da_xac_nhan", "Đã xác nhận"),
                            ("da_huy", "Đã hủy"),
                            ("hoan_thanh", "Hoàn thành"),
                        ],
                        default="cho_xac_nhan",
                        max_length=20,
                    ),
                ),
                ("mo_ta", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
