# Generated by Django 5.1.8 on 2025-05-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="nganh",
            new_name="khoa",
        ),
        migrations.AddField(
            model_name="doctor",
            name="chuc_vu",
            field=models.CharField(
                choices=[
                    ("truong_khoa", "Trưởng khoa"),
                    ("pho_khoa", "Phó khoa"),
                    ("bac_si", "Bác sĩ"),
                ],
                default="bac_si",
                max_length=50,
            ),
        ),
    ]
